[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The AI Writing Genius: Strategies and Techniques for Collaborating with Artificial Intelligence for Better Writing Outcomes"
